### ISSUE TITLE
Redundant double scroll appears on iFrame cards

### ISSUE THREAD

**Issue by polinavgmailcom** [ConfigurableUIComponents/configurable-interactive-layout#24]
Redundant double vertical scroll appears on iFrame cards.
![image](https://user-images.githubusercontent.com/36443439/36150084-1087cef6-10cb-11e8-89ef-7f67c85b5918.png)

**Comment by ConfigurableUIComponents** [comment]
fixed. see https://configurableuicomponents.github.io/configurable-interactive-layout-sandbox/index.html (you might need to clear you cache to get the latest)
